### ISSUE TITLE
Youtube video description constructor is working

### ISSUE THREAD

**Issue by thealmamun** [100lvlmaster/youtube_metadata#1]
Hi, 
I have to pull the description of yt video, but I have seen there's no option for that. is there any plan to add it?

**Comment by 100lvlmaster** [comment]
https://github.com/100lvlmaster/youtube_metadata/pull/2
added it in version 1.0.1

**Comment by 100lvlmaster** [comment]
the description option is added, ill be closing this issue now, 
![noragami](https://pm1.narvii.com/6106/c35196ce89ea8e012d820550e03db6ae97dd00cd_hq.jpg)
